language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "8.0"
  - "7"
  - "6"

sudo: false

install:
  - npm install

script:
  - npm run shim:lint
  - npm run shim:build
  - npm run shim:test

after_success:
  - npm run shim:coverage && npm run shim:coveralls

branches:
  only:
    - master

matrix:
  allow_failures:
    - node_js: "8.0"
    - node_js: "7"
    - node_js: "6"
